// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    GetHealth429Response,
    GetV1RunnerModels200Response,
    PostV1RunnerChat200Response,
    PostV1RunnerChatRequest,
    PostV1RunnerGenerateRequest,
} from '../models';

export interface PostV1RunnerChatRequest {
    postV1RunnerChatRequest: PostV1RunnerChatRequest;
}

export interface PostV1RunnerGenerateRequest {
    postV1RunnerGenerateRequest: PostV1RunnerGenerateRequest;
}

/**
 * no description
 */
export class RunnerApi extends BaseAPI {

    /**
     * 
     * List configured runner model routes
     */
    getV1RunnerModels(): Observable<GetV1RunnerModels200Response>
    getV1RunnerModels(opts?: OperationOpts): Observable<AjaxResponse<GetV1RunnerModels200Response>>
    getV1RunnerModels(opts?: OperationOpts): Observable<GetV1RunnerModels200Response | AjaxResponse<GetV1RunnerModels200Response>> {
        const headers: HttpHeaders = {
        };

        return this.request<GetV1RunnerModels200Response>({
            url: '/v1/runner/models',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

    /**
     * 
     * Multi-turn chat completion
     */
    postV1RunnerChat({ postV1RunnerChatRequest }: PostV1RunnerChatRequest): Observable<PostV1RunnerChat200Response>
    postV1RunnerChat({ postV1RunnerChatRequest }: PostV1RunnerChatRequest, opts?: OperationOpts): Observable<AjaxResponse<PostV1RunnerChat200Response>>
    postV1RunnerChat({ postV1RunnerChatRequest }: PostV1RunnerChatRequest, opts?: OperationOpts): Observable<PostV1RunnerChat200Response | AjaxResponse<PostV1RunnerChat200Response>> {
        throwIfNullOrUndefined(postV1RunnerChatRequest, 'postV1RunnerChatRequest', 'postV1RunnerChat');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<PostV1RunnerChat200Response>({
            url: '/v1/runner/chat',
            method: 'POST',
            headers,
            body: postV1RunnerChatRequest,
        }, opts?.responseOpts);
    };

    /**
     * 
     * Single-prompt generation
     */
    postV1RunnerGenerate({ postV1RunnerGenerateRequest }: PostV1RunnerGenerateRequest): Observable<PostV1RunnerChat200Response>
    postV1RunnerGenerate({ postV1RunnerGenerateRequest }: PostV1RunnerGenerateRequest, opts?: OperationOpts): Observable<AjaxResponse<PostV1RunnerChat200Response>>
    postV1RunnerGenerate({ postV1RunnerGenerateRequest }: PostV1RunnerGenerateRequest, opts?: OperationOpts): Observable<PostV1RunnerChat200Response | AjaxResponse<PostV1RunnerChat200Response>> {
        throwIfNullOrUndefined(postV1RunnerGenerateRequest, 'postV1RunnerGenerateRequest', 'postV1RunnerGenerate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<PostV1RunnerChat200Response>({
            url: '/v1/runner/generate',
            method: 'POST',
            headers,
            body: postV1RunnerGenerateRequest,
        }, opts?.responseOpts);
    };

}
