// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts } from '../runtime';
import type {
    GetHealth200Response,
    GetHealth429Response,
} from '../models';

/**
 * no description
 */
export class SystemApi extends BaseAPI {

    /**
     * Returns server health status
     * Health check
     */
    getHealth(): Observable<GetHealth200Response>
    getHealth(opts?: OperationOpts): Observable<AjaxResponse<GetHealth200Response>>
    getHealth(opts?: OperationOpts): Observable<GetHealth200Response | AjaxResponse<GetHealth200Response>> {
        return this.request<GetHealth200Response>({
            url: '/health',
            method: 'GET',
        }, opts?.responseOpts);
    };

}
