// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Meta,
} from './';

/**
 * @export
 * @interface GetHealth200Response
 */
export interface GetHealth200Response {
    /**
     * @type {string}
     * @memberof GetHealth200Response
     */
    data?: string;
    /**
     * @type {Error}
     * @memberof GetHealth200Response
     */
    error?: Error;
    /**
     * @type {Meta}
     * @memberof GetHealth200Response
     */
    meta?: Meta;
    /**
     * @type {boolean}
     * @memberof GetHealth200Response
     */
    success: boolean;
}
