// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    GetV1RunnerModels200ResponseData,
    Meta,
} from './';

/**
 * @export
 * @interface GetV1RunnerModels200Response
 */
export interface GetV1RunnerModels200Response {
    /**
     * @type {GetV1RunnerModels200ResponseData}
     * @memberof GetV1RunnerModels200Response
     */
    data?: GetV1RunnerModels200ResponseData;
    /**
     * @type {Error}
     * @memberof GetV1RunnerModels200Response
     */
    error?: Error;
    /**
     * @type {Meta}
     * @memberof GetV1RunnerModels200Response
     */
    meta?: Meta;
    /**
     * @type {boolean}
     * @memberof GetV1RunnerModels200Response
     */
    success: boolean;
}
