// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Meta
 */
export interface Meta {
    /**
     * @type {string}
     * @memberof Meta
     */
    duration?: string;
    /**
     * @type {number}
     * @memberof Meta
     */
    page?: number;
    /**
     * @type {number}
     * @memberof Meta
     */
    per_page?: number;
    /**
     * @type {string}
     * @memberof Meta
     */
    request_id?: string;
    /**
     * @type {number}
     * @memberof Meta
     */
    total?: number;
}
