// tslint:disable
/**
 * lthn API
 * Lethean Desktop HTTP gateway — same surface the WebView reaches via Wails bindings, exposed to external clients and the plugin market.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    PostV1RunnerChatRequestMessagesInner,
} from './';

/**
 * @export
 * @interface PostV1RunnerChatRequest
 */
export interface PostV1RunnerChatRequest {
    /**
     * @type {Array<PostV1RunnerChatRequestMessagesInner>}
     * @memberof PostV1RunnerChatRequest
     */
    messages: Array<PostV1RunnerChatRequestMessagesInner>;
}
